# Generated by Django 4.1.2 on 2022-11-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_cal_access_expiry_profile_cal_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cal_access_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
