# Generated by Django 4.1.2 on 2022-10-24 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name of the Tier')),
                ('multiplier', models.IntegerField(default=1, verbose_name='Multiplier points of the project')),
            ],
        ),
    ]
