# Generated by Django 4.1.2 on 2022-11-29 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_alter_quizhistory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizhistory',
            name='category',
            field=models.IntegerField(choices=[(23, 'History'), (9, 'General Knowledge'), (17, 'Science'), (27, 'Animals'), (10, 'Books'), (11, 'Movies')]),
        ),
    ]
