# Generated by Django 4.1.2 on 2022-11-29 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0006_alter_quizhistory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizhistory',
            name='category',
            field=models.IntegerField(choices=[(11, 'Movies'), (10, 'Books'), (23, 'History'), (17, 'Science'), (9, 'General Knowledge'), (27, 'Animals')]),
        ),
    ]
